name: Docker Build Image

# on:
#   release:
#     types: [published, created, edited]
    
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set Version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile --tag rubenskj/portfolio-web:$RELEASE_VERSION

    - name: Publish
      run: |-
        docker push rubenskj/portfolio-web:$RELEASE_VERSION
